import React, { useState, useEffect, useCallback } from "react";
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Feather } from "@expo/vector-icons";
import { colors, typography, spacing, radius } from "../../theme/tokens";
import { api, getProjectId } from "../../lib/api";
import { useProxy } from "../../context/ProxyContext";
import { Button } from "../../components/ui/Button";
import { FilterPanel } from "../../components/ui/FilterPanel";
import { SelectBox } from "../../components/ui/SelectBox";
import { getBeltColor, normalizeModalityKey, NO_GRADUATION_COLOR } from "../../lib/belts";
import { JustifyAbsenceScreen } from "./JustifyAbsenceScreen";

/** Days after the aula's date during which "Justificar" is offered — must
 * mirror the backend's `_JUSTIFY_PRAZO_DAYS` (app/routers/attendance.py).
 * This is a display-only heuristic (based on `dateSort`, a date without
 * time-of-day); the server is authoritative and re-validates on submit. */
const JUSTIFY_PRAZO_DAYS = 7;

function withinJustifyPrazo(dateSort: string): boolean {
  const parts = dateSort.split("-").map(Number);
  if (parts.length !== 3 || parts.some((n) => Number.isNaN(n))) return false;
  const [y, m, d] = parts;
  const deadline = new Date(y, m - 1, d);
  deadline.setDate(deadline.getDate() + JUSTIFY_PRAZO_DAYS + 1); // exclusive end-of-day
  return new Date() < deadline;
}

/** Synthetic placeholder ids (`absent_{dateSort}`) are generated by the
 * backend's `_build_month_records` (app/services/attendance_service.py) for
 * scheduled class days with no real Firestore attendance doc. There is
 * nothing to justify for these — only real absence docs (id = Firestore
 * doc id) are justifiable. */
function isRealRecordId(id: string): boolean {
  return !id.startsWith("absent_");
}

/* ── Types (mirror app/models/attendance.py, camelCase over the wire) ──── */

type AttendanceStatus =
  | "registered"
  | "confirmed"
  | "absent"
  | "absent_justified"
  | "absent_justification_pending";

interface AttendanceRecord {
  id: string;
  date: string;
  dateSort: string;
  modalityName: string;
  teacherName?: string | null;
  status: AttendanceStatus;
  statusLabel: string;
  justification?: string | null;
}

interface MonthSummary {
  month: string;         // "2026-07"
  monthLabel: string;    // "Julho / 2026"
  attended: number;
  total: number;
  percent: number;
  records: AttendanceRecord[];
}

interface AttendanceCounts {
  confirmed: number;
  absent: number;
  absentJustified: number;
  justificationPending: number;
  awaitingConfirmation: number;
}

interface GraduationBreakdown {
  key: string;                 // "{belt}:{degree}" | "no_graduation"
  belt: string | null;
  degree: number | null;
  pending: boolean;
  counts: AttendanceCounts;
  percent: number | null;      // ratio 0..1, null when denominator is 0
}

interface AttendanceHistory {
  streakDays: number;
  overallPercent: number;
  months: MonthSummary[];
  counts: AttendanceCounts;
  percent: number | null;      // ratio 0..1
  byGraduation: GraduationBreakdown[];
}

interface ModalityOut {
  id: string;
  name: string;
  slug: string;
}

interface GraduationEntry {
  belt: string;
  degree: number;
}

interface ProfileData {
  graduation: Record<string, GraduationEntry> | null;
}

interface ModalityOption {
  name: string;
  slug: string;
}

interface GraduationFilter {
  key: string;
  belt: string;
  degree: number | null;
}

type Screen = "loading" | "ready" | "empty" | "error";

/* ── Status badge config (5 estados) ──────────────────────────────────── */

const STATUS_META: Record<
  AttendanceStatus,
  { bg: string; text: string; icon: keyof typeof Feather.glyphMap }
> = {
  confirmed: { bg: "rgba(76,175,80,0.15)", text: colors.success, icon: "check-circle" },
  absent: { bg: "rgba(239,68,68,0.15)", text: colors.error, icon: "x-circle" },
  absent_justified: { bg: "rgba(198,163,78,0.15)", text: colors.primary, icon: "shield" },
  absent_justification_pending: { bg: "rgba(245,158,11,0.15)", text: colors.warning, icon: "clock" },
  registered: { bg: "rgba(153,153,153,0.15)", text: colors.mutedForeground, icon: "help-circle" },
};

/* ── Helpers ───────────────────────────────────────────────────────────── */

function formatPercent(ratio: number | null): string {
  if (ratio === null) return "—";
  return `${Math.round(ratio * 100)}%`;
}

function graduationLabel(g: { belt: string | null; degree: number | null }): string {
  if (!g.belt) return "Sem graduação";
  return g.degree ? `${g.belt} · grau ${g.degree}` : g.belt;
}

function trackWidths(counts: AttendanceCounts) {
  const denom = counts.confirmed + counts.absent + counts.justificationPending;
  if (denom === 0) return { ok: 0, rev: 0, miss: 0 };
  return {
    ok: (counts.confirmed / denom) * 100,
    rev: (counts.justificationPending / denom) * 100,
    miss: (counts.absent / denom) * 100,
  };
}

function buildQuery(params: Record<string, string | number | undefined | null>): string {
  const usp = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null && v !== "") usp.set(k, String(v));
  }
  const qs = usp.toString();
  return qs ? `?${qs}` : "";
}

/* ── Component ─────────────────────────────────────────────────────────── */

interface FrequencyHistoryScreenProps {
  onBack: () => void;
}

export function FrequencyHistoryScreen({ onBack }: FrequencyHistoryScreenProps) {
  const { actingAs, actingAsName } = useProxy();
  const [screen, setScreen] = useState<Screen>("loading");
  const [data, setData] = useState<AttendanceHistory | null>(null);
  const [breakdownGroups, setBreakdownGroups] = useState<GraduationBreakdown[]>([]);
  const [breakdownLoading, setBreakdownLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);

  const [modalityOptions, setModalityOptions] = useState<ModalityOption[]>([]);
  const [currentGraduation, setCurrentGraduation] = useState<Record<string, GraduationEntry>>({});

  const [selectedMonth, setSelectedMonth] = useState<string | null>(null);
  const [selectedModality, setSelectedModality] = useState<ModalityOption | null>(null);
  const [selectedGraduation, setSelectedGraduation] = useState<GraduationFilter | null>(null);
  const [filtersReady, setFiltersReady] = useState(false);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [justifyTarget, setJustifyTarget] = useState<AttendanceRecord | null>(null);

  const authHeaders = useCallback((): Record<string, string> => {
    const headers: Record<string, string> = {};
    if (actingAs) headers["X-Acting-As"] = actingAs;
    return headers;
  }, [actingAs]);

  /* Bootstrap: modalities + unfiltered history + profile graduation. */
  const bootstrap = useCallback(async () => {
    setScreen("loading");
    setFiltersReady(false);
    try {
      const headers = authHeaders();
      const projectId = getProjectId();
      const [history, modalitiesRes, profile] = await Promise.all([
        api.get<AttendanceHistory>("/attendance/history", { headers }),
        api.get<{ modalities: ModalityOut[] }>(`/projects/${projectId}/modalities`),
        api.get<ProfileData>("/users/me/profile", { headers }),
      ]);

      setData(history);
      setCurrentGraduation(profile.graduation ?? {});

      const namesInRecords = new Set<string>();
      history.months.forEach((m) =>
        m.records.forEach((r) => { if (r.modalityName) namesInRecords.add(r.modalityName); }),
      );
      const options = modalitiesRes.modalities
        .filter((mod) => namesInRecords.has(mod.name))
        .map((mod) => ({ name: mod.name, slug: mod.slug }));
      setModalityOptions(options);

      const hasRecords = history.months.some((m) => m.records.length > 0);
      setScreen(hasRecords ? "ready" : "empty");

      // Default dos filtros: mês mais recente disponível (o backend já corta
      // pela data-base da turma), modalidade e graduação em "Todas" — é o
      // estado que o ícone de filtro considera "sem filtro aplicado".
      setSelectedMonth(history.months[0]?.month ?? null);
      setSelectedModality(null);
      setSelectedGraduation(null);
      setFiltersReady(true);
    } catch {
      setScreen("error");
    }
  }, [authHeaders]);

  useEffect(() => { bootstrap(); }, [bootstrap]);

  /* Scoped fetch: honours month + modality + graduação (the 3 chained filters). */
  useEffect(() => {
    if (!filtersReady) return;
    let cancelled = false;
    (async () => {
      setRefreshing(true);
      try {
        const qs = buildQuery({
          month: selectedMonth ?? undefined,
          modality: selectedModality?.slug,
          belt: selectedGraduation?.belt,
          degree: selectedGraduation ? selectedGraduation.degree ?? undefined : undefined,
        });
        const res = await api.get<AttendanceHistory>(`/attendance/history${qs}`, { headers: authHeaders() });
        if (!cancelled) setData(res);
      } catch {
        if (!cancelled) setScreen("error");
      } finally {
        if (!cancelled) setRefreshing(false);
      }
    })();
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedMonth, selectedModality, selectedGraduation, filtersReady, actingAs]);

  /* Breakdown fetch: month + modality only (never belt/degree) — feeds both
   * the graduação chip options and the "Recorte por graduação" cards. */
  useEffect(() => {
    if (!filtersReady) return;
    if (!selectedModality) { setBreakdownGroups([]); return; }
    let cancelled = false;
    (async () => {
      setBreakdownLoading(true);
      try {
        const qs = buildQuery({ month: selectedMonth ?? undefined, modality: selectedModality.slug });
        const res = await api.get<AttendanceHistory>(`/attendance/history${qs}`, { headers: authHeaders() });
        if (!cancelled) setBreakdownGroups(res.byGraduation);
      } catch {
        if (!cancelled) setBreakdownGroups([]);
      } finally {
        if (!cancelled) setBreakdownLoading(false);
      }
    })();
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedMonth, selectedModality, filtersReady, actingAs]);

  /* ── Justificar falta (Task B7) ── */
  if (justifyTarget) {
    return (
      <JustifyAbsenceScreen
        record={{
          id: justifyTarget.id,
          date: justifyTarget.date,
          modalityName: justifyTarget.modalityName,
        }}
        onClose={() => setJustifyTarget(null)}
        onJustified={() => {
          setJustifyTarget(null);
          bootstrap();
        }}
      />
    );
  }

  /* ── Loading ── */
  if (screen === "loading") {
    return (
      <SafeAreaView style={styles.safe} edges={["top"]}>
        <ScreenHeader onBack={onBack} subtitle={actingAsName ? `Frequência de ${actingAsName}` : undefined} />
        <View style={styles.center}>
          <ActivityIndicator size="large" color={colors.primary} />
        </View>
      </SafeAreaView>
    );
  }

  /* ── Error ── */
  if (screen === "error") {
    return (
      <SafeAreaView style={styles.safe} edges={["top"]}>
        <ScreenHeader onBack={onBack} />
        <View style={styles.center}>
          <View style={styles.emptyIcon}>
            <Feather name="alert-triangle" size={28} color={colors.error} />
          </View>
          <Text style={styles.emptyTitle}>Não foi possível carregar</Text>
          <Text style={styles.emptyMsg}>
            Verifique sua conexão e tente novamente.
          </Text>
          <View style={styles.retryWrap}>
            <Button label="Tentar novamente" onPress={bootstrap} />
          </View>
        </View>
      </SafeAreaView>
    );
  }

  /* ── Empty ── */
  if (screen === "empty" || !data) {
    return (
      <SafeAreaView style={styles.safe} edges={["top"]}>
        <ScreenHeader onBack={onBack} subtitle={actingAsName ? `Frequência de ${actingAsName}` : undefined} />
        <View style={styles.center}>
          <View style={styles.emptyIcon}>
            <Feather name="calendar" size={28} color={colors.mutedForeground} />
          </View>
          <Text style={styles.emptyTitle}>Nenhum registro</Text>
          <Text style={styles.emptyMsg}>
            Seus dados de frequência aparecerão aqui após o primeiro check-in.
          </Text>
        </View>
      </SafeAreaView>
    );
  }

  /* ── Ready ── */
  const monthOptions = data.months;
  const selectedMonthSummary = monthOptions.find((m) => m.month === selectedMonth) ?? monthOptions[0];
  const monthRecordsAll = selectedMonthSummary?.records ?? [];
  const monthRecords = selectedModality
    ? monthRecordsAll.filter((r) => r.modalityName === selectedModality.name)
    : monthRecordsAll;

  const widths = trackWidths(data.counts);

  // "Current" graduation group for the selected modality (highlighted, no
  // "Faixa anterior" tag); everything else in scope is archived.
  const currentEntry = selectedModality
    ? currentGraduation[normalizeModalityKey(selectedModality.name)]
    : undefined;
  const gradedGroups = breakdownGroups.filter((g) => g.key !== "no_graduation" && g.belt);
  const noGraduationGroup = breakdownGroups.find((g) => g.key === "no_graduation");
  let currentGroup = currentEntry
    ? gradedGroups.find((g) => g.belt === currentEntry.belt && g.degree === currentEntry.degree)
    : undefined;
  if (!currentGroup && gradedGroups.length === 1) currentGroup = gradedGroups[0];
  const archivedGroups = gradedGroups.filter((g) => g.key !== currentGroup?.key);

  // Ponto dourado no ícone: algum filtro fora do default (mês mais recente,
  // modalidade e graduação em "Todas").
  const filterActive =
    !!selectedModality ||
    !!selectedGraduation ||
    (!!selectedMonth && selectedMonth !== monthOptions[0]?.month);

  return (
    <SafeAreaView style={styles.safe} edges={["top"]}>
      <ScreenHeader
        onBack={onBack}
        subtitle={actingAsName ? `Frequência de ${actingAsName}` : undefined}
        onFilter={() => setFiltersOpen(true)}
        filterActive={filterActive}
      />
      <ScrollView
        contentContainerStyle={styles.scroll}
        showsVerticalScrollIndicator={false}
      >
        {/* KPIs */}
        <View style={styles.kpiRow}>
          <View style={[styles.kpi, styles.kpiHero]}>
            <Text style={styles.kpiValueHero}>{formatPercent(data.percent)}</Text>
            <Text style={styles.kpiLabel}>Frequência</Text>
          </View>
          <View style={styles.kpi}>
            <Text style={styles.kpiValue}>🔥{data.streakDays}</Text>
            <Text style={styles.kpiLabel}>Sequência</Text>
          </View>
          <View style={styles.kpi}>
            <Text style={styles.kpiValue}>{data.counts.confirmed}</Text>
            <Text style={styles.kpiLabel}>Presenças</Text>
          </View>
        </View>
        {refreshing && (
          <ActivityIndicator size="small" color={colors.primary} style={styles.refreshSpinner} />
        )}

        {/* Resumo do mês */}
        <Text style={styles.sectionTitle}>RESUMO DO MÊS</Text>
        <View style={styles.monthCard}>
          <View style={styles.monthTop}>
            <Text style={styles.monthLabel}>{selectedMonthSummary?.monthLabel ?? "—"}</Text>
            <Text style={styles.monthPercent}>{formatPercent(data.percent)}</Text>
          </View>
          <View style={styles.track}>
            {widths.ok > 0 && <View style={[styles.trackFill, { width: `${widths.ok}%`, backgroundColor: colors.success }]} />}
            {widths.rev > 0 && <View style={[styles.trackFill, { width: `${widths.rev}%`, backgroundColor: colors.warning }]} />}
            {widths.miss > 0 && <View style={[styles.trackFill, { width: `${widths.miss}%`, backgroundColor: colors.error }]} />}
          </View>
          <View style={styles.legend}>
            <LegendItem color={colors.success} text={`${data.counts.confirmed} confirmadas`} />
            <LegendItem color={colors.warning} text={`${data.counts.justificationPending} em análise`} />
            <LegendItem color={colors.error} text={`${data.counts.absent} faltas`} />
            <LegendItem color={colors.primary} text={`${data.counts.absentJustified} justificada${data.counts.absentJustified === 1 ? "" : "s"}`} />
          </View>
        </View>

        {/* Recorte por graduação */}
        <Text style={styles.sectionTitle}>RECORTE POR GRADUAÇÃO</Text>
        {!selectedModality ? (
          <Text style={styles.hint}>Selecione uma modalidade para ver o recorte por graduação.</Text>
        ) : breakdownLoading ? (
          <ActivityIndicator size="small" color={colors.primary} style={styles.refreshSpinner} />
        ) : gradedGroups.length === 0 && !noGraduationGroup ? (
          <Text style={styles.hint}>Sem registros nesta modalidade no período selecionado.</Text>
        ) : (
          <View style={{ gap: spacing.sm + 4 }}>
            {currentGroup && (
              <GraduationCard
                group={currentGroup}
                modalityName={selectedModality.name}
                archived={false}
              />
            )}
            {archivedGroups.map((g) => (
              <GraduationCard
                key={g.key}
                group={g}
                modalityName={selectedModality.name}
                archived
              />
            ))}
            {noGraduationGroup && (
              <GraduationCard group={noGraduationGroup} modalityName={selectedModality.name} archived />
            )}
          </View>
        )}

        {/* Presenças recentes */}
        <Text style={styles.sectionTitle}>PRESENÇAS RECENTES</Text>
        {monthRecords.length === 0 ? (
          <Text style={styles.hint}>Nenhum registro para este filtro.</Text>
        ) : (
          <View style={styles.recordList}>
            {monthRecords.map((r) => (
              <RecordRow
                key={r.id}
                record={r}
                canJustify={
                  r.status === "absent" &&
                  isRealRecordId(r.id) &&
                  withinJustifyPrazo(r.dateSort)
                }
                // Falta real fora do prazo: em vez de simplesmente não ter
                // botão (que lê como "a função não existe"), diz o motivo.
                prazoExpired={
                  r.status === "absent" &&
                  isRealRecordId(r.id) &&
                  !withinJustifyPrazo(r.dateSort)
                }
                onJustify={() => setJustifyTarget(r)}
              />
            ))}
          </View>
        )}
      </ScrollView>

      {/* Filtros — padrão do app: ícone no header, painel pela direita */}
      <FilterPanel
        visible={filtersOpen}
        onClose={() => setFiltersOpen(false)}
        title="Filtros"
      >
        <View style={styles.filterSection}>
          <Text style={styles.filterSectionTitle}>Período</Text>
          <SelectBox
            value={selectedMonth}
            placeholder="Selecione o mês"
            options={monthOptions.map((m) => ({
              value: m.month,
              label: m.monthLabel,
            }))}
            onChange={setSelectedMonth}
          />
        </View>

        {modalityOptions.length > 0 && (
          <View style={styles.filterSection}>
            <Text style={styles.filterSectionTitle}>Modalidade</Text>
            <View style={styles.chipsWrap}>
              <Chip
                label="Todas"
                active={!selectedModality}
                onPress={() => { setSelectedModality(null); setSelectedGraduation(null); }}
              />
              {modalityOptions.map((mod) => (
                <Chip
                  key={mod.slug}
                  label={mod.name}
                  active={selectedModality?.slug === mod.slug}
                  onPress={() => { setSelectedModality(mod); setSelectedGraduation(null); }}
                />
              ))}
            </View>
          </View>
        )}

        {selectedModality && gradedGroups.length > 0 && (
          <View style={styles.filterSection}>
            <Text style={styles.filterSectionTitle}>Graduação</Text>
            <View style={styles.chipsWrap}>
              <Chip label="Todas" active={!selectedGraduation} onPress={() => setSelectedGraduation(null)} />
              {gradedGroups.map((g) => (
                <Chip
                  key={g.key}
                  label={graduationLabel(g)}
                  active={selectedGraduation?.key === g.key}
                  onPress={() => setSelectedGraduation({ key: g.key, belt: g.belt!, degree: g.degree })}
                />
              ))}
            </View>
          </View>
        )}
      </FilterPanel>
    </SafeAreaView>
  );
}

/* ── Subcomponents ─────────────────────────────────────────────────────── */

function ScreenHeader({
  onBack,
  subtitle,
  onFilter,
  filterActive = false,
}: {
  onBack: () => void;
  subtitle?: string;
  onFilter?: () => void;
  filterActive?: boolean;
}) {
  return (
    <View style={styles.header}>
      <Feather
        name="chevron-left"
        size={24}
        color={colors.foreground}
        onPress={onBack}
      />
      <View style={styles.headerCenter}>
        <Text style={styles.headerTitle}>Minha Frequência</Text>
        {subtitle && <Text style={styles.headerSubtitle}>{subtitle}</Text>}
      </View>
      {onFilter ? (
        <TouchableOpacity
          style={styles.headerAction}
          activeOpacity={0.7}
          onPress={onFilter}
          accessibilityRole="button"
          accessibilityLabel="Filtros"
        >
          <Feather
            name="sliders"
            size={22}
            color={filterActive ? colors.primary : colors.foreground}
          />
          {filterActive && <View style={styles.filterDot} />}
        </TouchableOpacity>
      ) : (
        <View style={styles.headerSpacer} />
      )}
    </View>
  );
}

function Chip({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) {
  return (
    <TouchableOpacity
      style={[styles.chip, active && styles.chipActive]}
      onPress={onPress}
      activeOpacity={0.8}
    >
      <Text style={[styles.chipText, active && styles.chipTextActive]}>{label}</Text>
    </TouchableOpacity>
  );
}

function LegendItem({ color, text }: { color: string; text: string }) {
  return (
    <View style={styles.legendItem}>
      <View style={[styles.legendDot, { backgroundColor: color }]} />
      <Text style={styles.legendText}>{text}</Text>
    </View>
  );
}

function GraduationCard({
  group,
  modalityName,
  archived,
}: {
  group: GraduationBreakdown;
  modalityName: string;
  archived: boolean;
}) {
  const beltColor = group.belt ? getBeltColor(modalityName, group.belt) : NO_GRADUATION_COLOR;
  const widths = trackWidths(group.counts);
  return (
    <View style={[styles.gradCard, archived && styles.gradCardArchived]}>
      <View style={styles.gradHead}>
        <View style={styles.beltPill}>
          <View style={[styles.beltBar, { backgroundColor: beltColor }]} />
          {!!group.degree && (
            <View style={styles.pips}>
              {Array.from({ length: group.degree }).map((_, i) => (
                <View key={i} style={styles.pip} />
              ))}
            </View>
          )}
          <Text style={styles.beltText}>{graduationLabel(group)}</Text>
        </View>
        {group.pending && (
          <View style={styles.pendingTag}>
            <Text style={styles.pendingTagText}>EM ANÁLISE</Text>
          </View>
        )}
        {archived && <Text style={styles.archivedTag}>Faixa anterior</Text>}
      </View>
      <View style={styles.gradStats}>
        <GradStat value={group.counts.confirmed} label="Present." color={colors.success} />
        <GradStat value={group.counts.absent} label="Faltas" color={colors.error} />
        <GradStat value={group.counts.absentJustified} label="Justif." color={colors.primary} />
        <GradStat value={formatPercent(group.percent)} label="Freq." color={colors.foreground} />
      </View>
      <View style={styles.track}>
        {widths.ok > 0 && <View style={[styles.trackFill, { width: `${widths.ok}%`, backgroundColor: colors.success }]} />}
        {widths.rev > 0 && <View style={[styles.trackFill, { width: `${widths.rev}%`, backgroundColor: colors.warning }]} />}
        {widths.miss > 0 && <View style={[styles.trackFill, { width: `${widths.miss}%`, backgroundColor: colors.error }]} />}
      </View>
    </View>
  );
}

function GradStat({ value, label, color }: { value: number | string; label: string; color: string }) {
  return (
    <View style={styles.gradStat}>
      <Text style={[styles.gradStatValue, { color }]}>{value}</Text>
      <Text style={styles.gradStatLabel}>{label}</Text>
    </View>
  );
}

function RecordRow({
  record,
  canJustify,
  prazoExpired = false,
  onJustify,
}: {
  record: AttendanceRecord;
  canJustify: boolean;
  prazoExpired?: boolean;
  onJustify: () => void;
}) {
  const meta = STATUS_META[record.status] ?? STATUS_META.absent;
  return (
    <View style={styles.recordRow}>
      <View style={styles.recordInfo}>
        <Text style={styles.recordDate}>{record.date}</Text>
        <Text style={styles.recordSub}>
          {record.modalityName}
          {record.teacherName ? ` · ${record.teacherName}` : ""}
        </Text>
        {record.justification && (
          <Text style={styles.justification}>{record.justification}</Text>
        )}
      </View>
      <View style={styles.recordActions}>
        <View style={[styles.badge, { backgroundColor: meta.bg }]}>
          <Feather name={meta.icon} size={11} color={meta.text} />
          <Text style={[styles.badgeText, { color: meta.text }]}>{record.statusLabel}</Text>
        </View>
        {canJustify && (
          <TouchableOpacity style={styles.justifyBtn} onPress={onJustify} activeOpacity={0.8}>
            <Feather name="edit-3" size={11} color={colors.primary} />
            <Text style={styles.justifyBtnText}>Justificar</Text>
          </TouchableOpacity>
        )}
        {!canJustify && prazoExpired && (
          <Text style={styles.prazoExpired}>Prazo para justificar encerrado</Text>
        )}
      </View>
    </View>
  );
}

/* ── Styles ────────────────────────────────────────────────────────────── */

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.background,
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.xl,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    color: colors.foreground,
    fontFamily: typography.fontHeadingSemi,
    fontSize: 18,
  },
  headerSubtitle: {
    color: colors.mutedForeground,
    fontFamily: typography.fontBody,
    fontSize: 12,
    marginTop: 2,
  },
  headerSpacer: {
    width: 24,
  },
  headerAction: {
    width: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  filterDot: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.background,
  },
  scroll: {
    padding: spacing.md,
    paddingBottom: spacing.xxl,
  },

  // KPIs
  kpiRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  refreshSpinner: {
    marginTop: spacing.sm,
  },
  kpi: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing.md,
    gap: 3,
  },
  kpiHero: {
    borderColor: "rgba(198,163,78,0.4)",
    backgroundColor: "rgba(198,163,78,0.08)",
  },
  kpiValue: {
    color: colors.foreground,
    fontFamily: typography.fontHeading,
    fontSize: 22,
  },
  kpiValueHero: {
    color: colors.primary,
    fontFamily: typography.fontHeading,
    fontSize: 26,
  },
  kpiLabel: {
    color: colors.mutedForeground,
    fontFamily: typography.fontBodyMedium,
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },

  // Filters
  // Seções do painel de filtros — mesma convenção das telas de staff.
  filterSection: {
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  filterSectionTitle: {
    color: colors.mutedForeground,
    fontFamily: typography.fontBodyMedium,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: spacing.xs,
  },
  chipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs + 2,
  },
  chip: {
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: {
    fontSize: 12,
    fontFamily: typography.fontBodyMedium,
    color: colors.mutedForeground,
  },
  chipTextActive: {
    color: colors.primaryForeground,
    fontFamily: typography.fontBodySemiBold,
  },

  // Section title
  sectionTitle: {
    color: colors.mutedForeground,
    fontFamily: typography.fontHeadingSemi,
    fontSize: 12,
    letterSpacing: 1,
    marginTop: spacing.lg,
    marginBottom: spacing.sm + 4,
  },
  hint: {
    color: colors.mutedForeground,
    fontFamily: typography.fontBody,
    fontSize: 13,
    lineHeight: 19,
  },

  // Month summary card
  monthCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.sm + 2,
  },
  monthTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  monthLabel: {
    color: colors.foreground,
    fontFamily: typography.fontHeadingSemi,
    fontSize: 15,
  },
  monthPercent: {
    color: colors.foreground,
    fontFamily: typography.fontHeadingSemi,
    fontSize: 16,
  },
  track: {
    height: 8,
    borderRadius: radius.full,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
    flexDirection: "row",
  },
  trackFill: {
    height: 8,
  },
  legend: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm + 4,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 3,
  },
  legendText: {
    color: colors.mutedForeground,
    fontFamily: typography.fontBody,
    fontSize: 11,
  },

  // Graduation cards
  gradCard: {
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.sm + 2,
  },
  gradCardArchived: {
    opacity: 0.8,
  },
  gradHead: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  beltPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.full,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  beltBar: {
    width: 20,
    height: 11,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
  },
  pips: {
    flexDirection: "row",
    gap: 2,
  },
  pip: {
    width: 3,
    height: 11,
    borderRadius: 1,
    backgroundColor: colors.primary,
  },
  beltText: {
    color: colors.foreground,
    fontFamily: typography.fontHeadingSemi,
    fontSize: 12.5,
  },
  pendingTag: {
    backgroundColor: "rgba(245,158,11,0.15)",
    borderWidth: 1,
    borderColor: "rgba(245,158,11,0.4)",
    borderRadius: 6,
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  pendingTagText: {
    color: colors.warning,
    fontFamily: typography.fontBodySemiBold,
    fontSize: 10,
  },
  archivedTag: {
    marginLeft: "auto",
    color: colors.mutedForeground,
    fontFamily: typography.fontBody,
    fontSize: 12,
  },
  gradStats: {
    flexDirection: "row",
    gap: spacing.xs + 2,
  },
  gradStat: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: radius.md,
    paddingVertical: spacing.xs + 2,
  },
  gradStatValue: {
    fontFamily: typography.fontHeadingSemi,
    fontSize: 16,
  },
  gradStatLabel: {
    color: colors.mutedForeground,
    fontFamily: typography.fontBody,
    fontSize: 9,
    textTransform: "uppercase",
    letterSpacing: 0.3,
    marginTop: 2,
  },

  // Records
  recordList: {
    gap: 1,
  },
  recordRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: spacing.sm + 2,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  recordInfo: {
    flex: 1,
    gap: 2,
  },
  recordActions: {
    alignItems: "flex-end",
    gap: spacing.xs,
  },
  justifyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: "rgba(198,163,78,0.4)",
    backgroundColor: "rgba(198,163,78,0.08)",
  },
  justifyBtnText: {
    color: colors.primary,
    fontFamily: typography.fontBodySemiBold,
    fontSize: 10.5,
  },
  prazoExpired: {
    color: colors.mutedForeground,
    fontFamily: typography.fontBody,
    fontSize: 10,
    textAlign: "right",
  },
  recordDate: {
    color: colors.foreground,
    fontFamily: typography.fontBodyMedium,
    fontSize: 13,
  },
  recordSub: {
    color: colors.mutedForeground,
    fontFamily: typography.fontBody,
    fontSize: 11,
  },
  justification: {
    color: colors.mutedForeground,
    fontFamily: typography.fontBody,
    fontSize: 11,
    fontStyle: "italic",
    marginTop: 2,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.full,
  },
  badgeText: {
    fontFamily: typography.fontBodySemiBold,
    fontSize: 10.5,
  },

  // Empty / error state
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(153,153,153,0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.lg,
  },
  emptyTitle: {
    color: colors.foreground,
    fontFamily: typography.fontHeadingSemi,
    fontSize: 20,
    marginBottom: spacing.sm,
  },
  emptyMsg: {
    color: colors.mutedForeground,
    fontFamily: typography.fontBody,
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  retryWrap: {
    marginTop: spacing.lg,
    alignSelf: "stretch",
  },
});
